### ISSUE TITLE
ConfigurationLoader.getConfig() Causes Thread 15: EXC_BAD_ACCESS (code=1, address=0x4) Crash on Xcode 16 Beta 5

### ISSUE THREAD

**Issue by RGG-jayoung** [braintree/braintree_ios#1387] opened 2024-08-09 05:05 UTC
### Braintree SDK Version

6.23.1

### Environment

Both

### Xcode Version

Xcode 16 Beta 5

### OS Version & Device

iOS 18.0, iOS 18.1

### Integration type

Swfit Package Manager

### Development Processor

Apple Silicon (M-series chips)

### Describe the bug

When compiling with Xcode 16 beta 5 targeting iOS 15, 16, 17, 18 the `ConfigurationLoader.getConfig()` causes a crash, referencing `withCheckedThrowingContinuation` with a Thread 15: EXC_BAD_ACCESS (code=1, address=0x4) error.

<img width="1415" alt="Braintree Crash Configuration Loader" src="https://github.com/user-attachments/assets/9b6c74ad-ed19-416f-8338-c93c69936c50">

### To reproduce

1. Add Braintree via SPM
2. Follow Braintree docs for standard set up with BTAPIClient(authorization: clientToken) being called.
3. It is unclear when the `ConfigurationLoader.getConfig()` actually gets called, but after navigating through a few screens, it will be called, and after a considerable delay (10s++) the app will crash 

### Expected behavior

Braintree SDK should load without delay and not crash.

### Screenshots

<img width="1415" alt="Braintree Crash Configuration Loader" src="https://github.com/user-attachments/assets/b1660f75-b72a-4c48-ba25-7cb2915c3b39">
<img width="610" alt="image" src="https://github.com/user-attachments/assets/1ab805d3-b7cc-4ab8-bf1b-995a3ab36a58">

**Comment by jaxdesmarais** [comment] 2024-08-09 13:20
Hey @RGG-jayoung -

I believe this is a duplicate of #1382 - are you able to test out the branch in this comment and let us know the result: https://github.com/braintree/braintree_ios/issues/1382#issuecomment-2276561429.

**Comment by jaxdesmarais** [comment] 2024-08-12 23:02
@RGG-jayoung - Please let me know if [version 6.23.3](https://github.com/braintree/braintree_ios/releases/tag/6.23.3) resolves this issue

**Comment by jaxdesmarais** [comment] 2024-08-28 18:12
Closing due to inactivity, but please do let us know if [version 6.23.3](https://github.com/braintree/braintree_ios/releases/tag/6.23.3) did not resolve the issue and I would be happy to reopen this.

**Closed by jaxdesmarais** 2024-08-28 18:12 UTC
