### ISSUE TITLE
Invalid bundle when "rebuild with bitcode" is selected

### ISSUE THREAD

**Issue by phannindra** [braintree/braintree_ios#502] opened 2019-11-19 09:30 UTC
### General information

* Integration type and version:  Carthage 0.34.0

### Issue description

When I have uploaded an IPA in App store Distribution mode with the "Rebuild with bitcode" option selected I got a mail from Apple saying:(Upload was successful but in the Testflight it says "This build is invalid")

ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from:

https://urldefense.proofpoint.com/v2/url?u=https-3A__developer.apple.com_library_archive_technotes_tn2432_-5Findex.html&d=DwQFAw&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=GCuCuZ_pYPXqiqvG5wl4Vh3TlyIOLJUH9611UboigSw&m=Bl9uOklOQH-LzHst1L3UD9uMu596lMs7nY5FkRHPPy8&s=jt27O3Pfzqp9Q-7Q5xvPozp53z6ZUrT3bQnUvDzcxUw&e=

And Xcode is giving me this error when I'm trying to distribute the IPA with Ad-hoc distribution mode and Rebuilt with bitcode is selected

ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -L /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/ipatool20191119-15544-18tsjpm/thinned-out/armv7/Payload/Stage_Debug-Avance\ Care.app/Frameworks/BraintreeCard.framework -L /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/ipatool20191119-15544-18tsjpm/thinned-out/armv7/Payload/Stage_Debug-Avance\ Care.app/Frameworks/BraintreeCore.framework -L /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/ipatool20191119-15544-18tsjpm/thinned-out/armv7/Payload/Stage_Debug-Avance\ Care.app/Frameworks/PayPalOneTouch.framework -L /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/ipatool20191119-15544-18tsjpm/thinned-out/armv7/Payload/Stage_Debug-Avance\ Care.app/Frameworks/PayPalDataCollector.framework --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -o /var/folders/gk/9z9j8gcd5qq68x2v2tg881nm0000gp/T/ipatool20191119-15544-18tsjpm/thinned-out/armv7/Payload

**Please note that this error is only occurring when rebuild with bitcode is selected. Otherwise it is fine**

**Comment by scannillo** [comment] 2019-11-19 14:56
Hello @phannindra. Are you on the latest version of Xcode (11.2.1)? Also, which version of the Braintree SDK are you using?

After googling around a bit, looks like some other devs solved both similar issues by updating Xcode. Let us know, and we'll go from there!

**Comment by phannindra** [comment] 2019-11-22 06:10
Yes I have tried with 11.2.1 and it shows the same error

**Comment by scannillo** [comment] 2019-11-25 15:20
> Also, which version of the Braintree SDK are you using?

**Comment by phannindra** [comment] 2019-11-26 05:23
I am using Braintree 4.30.2.

**Comment by sestevens** [comment] 2019-12-02 17:11
@phannindra Please try including `PayPalUtils.framework` and let us know if this resolves the issue. This framework is required if you are using `PayPalOneTouch.framework` and `PayPalDataCollector.framework`.

I would also recommend updating to Braintree 4.30.2.

**Comment by phannindra** [comment] 2019-12-05 13:49
They are already included in **Frameworks, Libraries and Embedded Content** Section.
And are set to **Embed & Sign**

I have updated Braintree to 4.30.2 but it still won't work.

**Comment by sestevens** [comment] 2019-12-05 15:07
Could you provide a list of Braintree frameworks you're including in your project? So far, the only way I've been able to reproduce this issue is by excluding a required framework. Perhaps there is a different one missing.

**Comment by phannindra** [comment] 2019-12-05 16:33
Screenshots of the Braintree frameworks in the project:
![image](https://user-images.githubusercontent.com/13805549/70254249-c9752c00-17aa-11ea-909d-58d22ae2704d.png)
![image](https://user-images.githubusercontent.com/13805549/70254337-eb6eae80-17aa-11ea-8aaf-21856bfa1bab.png)

**Comment by demerino** [comment] 2019-12-05 18:38
@phannindra  Can you try including `BraintreeUnionPay` and trying again? It is required in the `podspec` but appears to be missing from our Carthage list in the README.

**Comment by phannindra** [comment] 2019-12-06 05:16
@demerino It still gives almost the same error after including BraintreeUnionPay framework

**Comment by sestevens** [comment] 2020-02-18 22:52
I'm going to close this issue since we're unable to reproduce it at this time.

**Closed by sestevens** 2020-02-18 22:52 UTC

**Comment by farshadtx** [comment] 2020-02-27 06:04
I have the same error when bitcode is enabled
- XCode: 11.3.1
- braintree_ios at "4.32.1"
- braintree-ios-drop-in at "8.0.0"

**Comment by callo90** [comment] 2020-03-10 19:03
Same thing here:

- XCode: 11.3.1
- braintree-ios-drop-in at "8.0.0"

Any clues?

**Comment by callo90** [comment] 2020-03-10 19:55
Found the error, you need to add cardinalMobile.framework
