### ISSUE TITLE
Integrate Kount via Swift Package Manager

### ISSUE THREAD

**Issue by ffittschen** [braintree/braintree_ios#837] opened 2022-07-12 10:20 UTC
**Is your feature request related to a problem? Please describe.**
As the BraintreeDataCollector links a vendored copy of the KountDataCollector.xcframework, we are getting duplicate symbol errors in our app, as we also link Kount ourselves. We cannot remove our vendored Kount and use the one shipped by Braintree, as KountDataCollector is only available within BraintreeDataCollector due to excluding the Kount headers from the package product.

**Describe the solution you'd like**
As a Braintree customer,
I want Kount to be declared as a Swift Package Manager dependency instead of being shipped as vendored copy,
so that the dependency manager can resolve the dependency graph and link Kount only once.

Kount publishes their SDK as a Swift Package in this repository: https://github.com/Kount/kount-ios-swift-package

By declaring Kount as external dependency instead of declaring it as a local binary target, customers of Braintree that also depend on Kount themselves would not be blocked with the integration of the Braintree SDK.

**Comment by jaxdesmarais** [comment] 2022-07-12 14:01
Hello @ffittschen -

Thanks for sharing those details on Kount. If you are using Kount directly outside of the legacy Braintree Kount integration, you should be able to use the `PayPalDataCollector` module instead of the `BraintreeDataCollector` module for data collection. Is there a particular integration path you are using that requires you to pull in both the `BraintreeDataCollector` module as well as your own Kount library directly?

**Comment by ffittschen** [comment] 2022-07-13 14:52
Hi @jaxdesmarais we are not using the `BraintreeDataCollector` so far, so the `PayPalDataCollector` will not help us.

The root cause of our problem is probably [this issue](https://github.com/tuist/tuist/issues/4599), as we are only facing the issue when running `tuist test`. Nevertheless, I'd say this feature request is valuable unrelated to the issue, as it's always better to let the dependency managers resolve compatible versions

**Comment by jaxdesmarais** [comment] 2022-07-13 15:39
Hello @ffittschen -

Thanks for following up! We have plans to fully deprecate Kount in the next major version of our SDK that will be released later this year. That said, it seems like the main issue is with how `tuist` resolves dependencies of packages that aren't in use by your project. 

In any case, we can certainly look into a different way to pull in Kount but would also need to ensure there is no regression the Kount SDK and what is published via SPM is a 1:1 of what is currently being pulled in. Additionally we will need to ensure that it works will all of the package managers we support (SPM, Carthage, and Cocoapods) but will certainly investigate this further and appreciate the suggestion.

**Comment by jaxdesmarais** [comment] 2022-08-04 18:23
Hello @ffittschen -

I wanted to reach back out with an update as we were able to investigate this further. At this time since Kount has only done 1 release via Swift Package Manager, we want to wait and see what their cadence will be with releasing update to their standard library as well as how quickly they release the same version via SPM. 

This is to ensure that if we were to go this route, we could update SPM, Carthage, and CocoaPods at the same time. Once we have a better idea of the release cadence from Kount across the package managers we will need to pull in, we will look into incorporating Kount more seamlessly across our package managers.

I see that your issue for `tuist` is still open - as this is on radar for a future task once Kount does their next release, do you want us to keep this issue open or resolve it on our side?

**Comment by ffittschen** [comment] 2022-08-05 16:11
Hi @jaxdesmarais, thanks for the update. As the release cadence of kount is pretty slow in general I'm assuming this will take a while.

The [tuist issue](https://github.com/tuist/tuist/issues/4599) is orthogonal, we are working on that topic at the moment. If you are not using GitHub issues as a tracker of things to be done, I don't mind if you close this issue and track it internally somewhere.

**Comment by jaxdesmarais** [comment] 2022-08-05 19:19
That sounds good, @ffittschen.

I'll close this out for now as it's not an issue with the Braintree SDK. I've also linked this issue internally so if we _do_ decide to move forward with this solution, we will be sure to reach back out here with an update for you. Thanks again for using the Braintree SDK and reaching out to us!

**Closed by jaxdesmarais** 2022-08-05 19:19 UTC
