### ISSUE TITLE
Static framework

### ISSUE THREAD

**Issue by AlexDenisov** [braintree/braintree_ios#148] opened 2015-07-27 09:29 UTC
Is it possible by any chance to get a statically built framework (using [iOS-Universal-Framework](https://github.com/kstenerud/iOS-Universal-Framework), for example)?
We don't use CocoaPods (for some reasons) and I've found out that the manual installation is a very painful and error prone process.

**Comment by burnto** [comment] 2015-07-27 13:22
Thanks. We're planning an update that will improve integration options, and we'll consider this approach for folks seeking legacy iOS 7 support (where dynamic frameworks aren't an option).

What do you feel is the actual advantage to the "static framework" hack vs just bare static lib .a and accompanying .h files? Just slightly simpler integration?

**Comment by AlexDenisov** [comment] 2015-07-27 13:38
> Just slightly simpler integration?
Yes, that is correct.
As for me static lib + headers are also a good idea, but with a framework it's much easier to integrate.

Let me know if you need some assistance with a static framework/library, I'd be more than happy to help you guys :)

**Comment by csknns** [comment] 2015-07-27 14:07
Perhaps the best solution is to use [Carthage] (https://github.com/Carthage/Carthage). If you provide a Cartfile for braintree it could automate the process of build a framework plus having all the advantages of a dependency management system.

**Comment by AlexDenisov** [comment] 2015-07-27 14:18
@csknns AFAIK, Cartage supports only dynamic frameworks, which is not the case.

**Comment by burnto** [comment] 2015-07-27 14:30
@csknns yes we are definitely planning on offering Carthage integration with the next major version, though that requires dynamic frameworks, which aren't supported/allowed for apps targeting back to iOS 7. Hence the discussion above about static lib/framework integrations. 

@AlexDenisov We do have static library experience if we go that route. The issue is more one of deployment and support across all these integration permutations. Thanks for your offer to help though!

**Comment by koppacetic** [comment] 2015-08-17 14:38
I'd like to second the motion of providing a static library plus resource bundle distribution. I have a requirement to support iOS 7 and using cocoapods is not an option.

**Comment by evgenyneu** [comment] 2015-08-23 03:28
@burnto It will be really helpful if you could add ability to build a dynamic framework file with Carthage. Right now we have to copy Braintree files into [a separate repository](https://github.com/exchangegroup/braintree-framework-builder) to be able to build it with Carthage, but this way we are missing out your updated. Thank you.

**Comment by burnto** [comment] 2015-08-23 15:48
Our next major version, coming very soon, will offer Carthage integration.

On Saturday, August 22, 2015, Evgenii Neumerzhitckii <
notifications@github.com> wrote:

> @burnto <https://github.com/burnto> It will be really helpful if you
> could add ability to build a dynamic framework file with Carthage. Right
> now we have to copy Braintree files into a separate repository
> <https://github.com/exchangegroup/braintree-framework-builder> to be able
> to build it with Carthage, but this way we are missing out your updated.
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/braintree/braintree_ios/issues/148#issuecomment-133777935>
> .
>


--

**Comment by mickeyreiss** [comment] 2015-09-03 21:29
@koppacetic one note on your request:

> I'd like to second the motion of providing a static library plus resource bundle distribution. I have a requirement to support iOS 7 and using cocoapods is not an option.

In our original design, we elected to avoid resources at all costs in order to simplify the integration to "code only" (i.e. static library). Our images have been [vectorized](https://github.braintreeps.com/braintree/braintree-ios/blob/master/Braintree/UI/Views/Vector%20Art/BTUIVisaVectorArtView.m), and our SSL certificates [encoded as an array](https://github.braintreeps.com/braintree/braintree-ios/blob/master/Braintree/API/Networking/Certificates/BTAPIPinnedCertificates.m). (The exception to this rule is localized strings, where we elected to use the platform standard `NSLocalizedString`.)

In light of this, are you requesting that we distribute our resources differently, or is it just the code distribution that you'd like to see us change?

**Comment by AlexDenisov** [comment] 2015-09-03 21:43
> In light of this, are you requesting that we distribute our resources differently, or is it just the code distribution that you'd like to see us change?

Question wasn't addressed to me, but I think that bundle might be an option, if you have to distribute resources separately.

**Comment by AlexDenisov** [comment] 2015-10-01 13:53
Hi there, do you guys have any updates?
_No pressure, just curious._

**Comment by skunkworks** [comment] 2015-10-01 15:58
Good news: there is a static framework target currently in the 4.0-beta branch. It's coming!

**Comment by Justin-Credible** [comment] 2016-03-07 19:09
Any updates on this? I ask because I don't see the 4.0 beta branch that @skunkworks mentioned.

**Comment by burnto** [comment] 2016-03-07 19:49
@Justin-Credible 4.0 is no longer a beta, so can now be found on master. 

Currently, we do not offer a prebuilt static library option. There is a static library target in the Braintree.xcodeproj project that can be added as a dependency, but it isn't a fully finished or documented option. We'll give some attention to static library docs.

Requests for static library support stopped in fall of last year (likely due to many developers dropping iOS 7 support and moving to dynamic frameworks), so we did not prioritize it.

**Comment by AlexDenisov** [comment] 2016-03-08 06:17
> Requests for static library support stopped in fall of last year (likely due to many developers dropping iOS 7 support and moving to dynamic frameworks), so we did not prioritize it.

Or they just gave up :)

**Comment by Justin-Credible** [comment] 2016-03-14 21:24
@burnto It would be useful for Cordova plugins. To get my plugin to work I had to manually build with Carthage, extract the framework bundles, and commit them to the plugin repo. It required a bit of hacking build hooks in Cordova to get the dynamic framework references working properly, and I think a static build would help in this situation at least.

**Comment by demerino** [comment] 2016-03-14 22:26
We'll be looking into documenting an `integrating with the static library target` this week.

**Comment by skunkworks** [comment] 2016-06-01 05:39
Hi everyone, in case you missed it, we recently added some documentation on [integrating the SDK as a static library](https://github.com/braintree/braintree_ios/blob/master/Docs/Braintree-Static-Integration-Guide.md). Let us know if you think it's too difficult or too easy or just right!

**Closed by skunkworks** 2016-06-01 05:39 UTC

**Comment by vdeep** [comment] 2016-12-23 13:13
I'm using XCode 8.1 and trying to include Braintree as a static framework following all the instructions mentioned on the above link. When I build the project it says "No such module 'Braintree'". I've followed all the instructions multiple times, each time getting the same error.

**Comment by skunkworks** [comment] 2016-12-23 18:06
@vdeep Because you're following the instructions correctly, it's likely there is some other Xcode configuration setting that is causing the compiler to be unable to link to the static library. Unfortunately, without your project in hand, it's hard for us to debug an issue like this.

If possible, I would recommend integrating via CocoaPods or Carthage.

**Comment by vdeep** [comment] 2016-12-23 18:35
I can't use either CocoaPods or Carthage due to my project restrictions. I've created a sample project [here](https://github.com/vdeep/BraintreeStaticIntegrationDemo). It is empty, I'm just including the `Braintree` library in `AppDelegate.swift`. It is giving the same error. It would really help if you can have a look.

**Comment by skunkworks** [comment] 2016-12-24 06:42
@vdeep The issue is that you cannot use `import Braintree` in your app delegate because you are linking to a static library. You will need to create a bridging header that imports the header files you need from the static library, e.g.

```objc
/// Bridging-Header.h

#import "BraintreeCore.h"
#import "BraintreeDropIn.h"
```

Let me know if that helps.

**Comment by vdeep** [comment] 2016-12-24 08:04
Thanks for your help @skunkworks. It is working :)
