### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by emrekyv** [braintree/braintree_ios#462] opened 2019-06-13 13:21 UTC
With iOS support for Swift Package Manager in Xcode 11, is there a way to get that added to the project?

**Comment by demerino** [comment] 2019-06-13 16:37
This is something that we're looking into and hope to have support for it.

**Comment by patchthecode** [comment] 2019-07-04 09:36
Any update on this?
Its pretty easy to add support for this. Simple add your code to a folder called Sources, and the add the Package.swift file. Would really be nice to have this

**Comment by scannillo** [comment] 2019-07-29 15:25
Hi @patchthecode. This is something on our future roadmap, however its priority is currently TBD.

**Comment by scannillo** [comment] 2019-07-29 15:26
Will leave this open to update once we get closer to its release.

**Comment by jeffc-dev** [comment] 2019-09-11 23:37
Is this something you'd accept a pull request for? It's pretty easy to add support for.

Xcode 11 is out and SwiftPM is now the "officially recommended" way of handling dependencies for iOS apps. We're currently working to migrate our existing code (and 3rd party code) as soon as possible.

**Comment by ethanwa** [comment] 2019-09-14 18:25
I would love to see this as well, thank you!

**Comment by pcabfever** [comment] 2019-10-23 14:18
Any updates on this? I would be awesome to have this

**Comment by sestevens** [comment] 2019-10-24 14:28
Hey @pcabfever 👋 We would definitely like to offer support for SPM at some point in the future, but we're juggling a few other priorities right now, so I can't give you a specific timeline for when it will be available. Since parts of the Braintree SDK depend on prebuilt binaries, we need to look into whether we can create a Swift package with a subset of the SDK's functionality. Otherwise, we may need to wait for support for prebuilt binaries to be added to Swift Package Manager.

**Comment by jamesyorke** [comment] 2020-02-12 16:27
Any movement on this? Fingers crossed for some good news

**Comment by sestevens** [comment] 2020-02-18 15:43
Hi @jamesyorke. We don't have much of an update at this point. We will most likely wait until prebuilt binaries can be added to SPM before we add support for it. We definitely plan to support Swift Package Manager in the future, though.

**Comment by thisolivier** [comment] 2020-03-16 15:48
Really glad to have an update. Given PayPal's clout, could Braintree look into sponsoring those binaries being published on SPM? Continuing to rely on CocoaPods is painful, and really at odds with Braintree's 'modern' sell.

**Comment by patchthecode** [comment] 2020-03-16 17:14
That's the trouble with big companies.. always long discussions. Meetings, red tape + extra back and forth resulting in years of deliberation for an important feature that can LITERALLY be added in less than 30 mins.

**Comment by demerino** [comment] 2020-03-16 19:48
@thisolivier We can raise the issue _again_ with our partners that own those binaries. Similarly, we'll keep an eye out for any updates to SPM/Xcode that would make it possible for us to support SPM.

We share your frustration and as we consider a major version bump we will revisit our SDK design to see if we can find a good solve for this if the prebuilt binary story doesn't budge.

**Comment by jeffc-dev** [comment] 2020-03-16 20:01
As a point of background for people asking about this.

Swift Package Manager currently only supports source-only packages. Binaries (ie. frameworks) are not supported.

It seems that the issue is that Braintree has closed-source code that they depend on in order to provide their functionality, and that is the hold-up. If this is the issue, their hands are tied.

There _is_ a Swift-Evolution proposal for binary support in SPM, but this is not supported yet in shipping versions.

https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md

It sounds like progress _is_ being made, however, and this SPM feature will likely land soon:

https://forums.swift.org/t/accepted-with-modifications-se-0272-package-manager-binary-dependencies/31926

My hope is that this will clear up the logjam and allow Braintree to proceed (hopefully soon, as we're really pushing to move to SPM for all our dependencies).

**Comment by demerino** [comment] 2020-03-16 20:43
@jeffc-dev thank you for the clarification and references.

**Comment by ethanwa** [comment] 2020-06-26 20:31
Xcode 12 and Swift 5.3 (both available as dev betas) now include resource and closed-source binary support. Hopefully SPM can now be done for this?

https://www.hackingwithswift.com/articles/218/whats-new-in-swift-5-3

**Comment by eseay** [comment] 2020-08-27 14:37
Is there any update on the progress to move BT to Swift PM? Even if for the time being it were just on a side branch, since it's only supported for Swift 5.3, it would still be helpful.

**Comment by ethanwa** [comment] 2020-09-16 16:04
Xcode 12 is now out as of today. SPM should be possible with Braintree I'd think at this point.

**Comment by bofeizhu** [comment] 2020-09-26 00:13
@sestevens Any updae on this issue? Xcode 12 supports SPM with prebuild binary now. Here is the related WWDC session https://developer.apple.com/videos/play/wwdc2020/10147 BrainTree is the sole framework that blocks us from moving to SPM now.

**Comment by natanrolnik** [comment] 2020-10-05 15:38
We're also willing to move to SPM. It already supports resources and prebuilt binaries.
Hopefully, it can come back to the top in the priorities for Braintree 🙏

**Comment by Dario-GoldenSpear** [comment] 2020-10-08 19:22
We are also on the same boat, SPM support would be great!.

**Comment by joseantsm-gs** [comment] 2020-10-09 09:38
Same here! We hope Braintree moves to SPM soon!

**Comment by scannillo** [comment] 2020-10-15 21:15
Hello everyone - we have been actively working on adding SPM support. 

Though Swift 5.3 does bring support for binary dependencies to SPM, only the `xcframework` format is currently supported ([see SE Proposal 0272](https://github.com/apple/swift-evolution/blob/master/proposals/0272-swiftpm-binary-dependencies.md#support-for-non-apple-platforms)). Two of the Braintree's dependencies (3DS and fraud detection) are not `.xcframework` binaries.

We have brought the issues to both of our partners. We will keep you posted!

**Comment by RamblinWreck77** [comment] 2020-10-15 21:27
@scannillo Thanks for the update! My understanding (and I may be wrong here) is that 3DS is an optional component you can enable. 

If that's the case would it be possible to have a "braintree core" without 3DS, enabling a basic integration sooner? 

Fraud protection sounds a little bit more scary, so maybe that one is best to wait for :P

**Comment by kokluch** [comment] 2020-11-17 08:48
Hi @scannillo would you have any news on this topic? Maybe an intermediate solution would be to provider Braintree as an xcframework itself. That's what we're doing while waiting for SPM support in an official release.

**Comment by scannillo** [comment] 2020-11-17 15:02
Hello @kokluch - we are actively working on SPM support. We plan to have a beta release of the SDK out soon with partial SPM support (while we wait for 2 of our 3rd party vendors to create xcframeworks). 

We will look into creating a Braintree xcframework in the meantime, though. Thank you for the suggestion. We will keep you updated.

**Comment by kokluch** [comment] 2020-11-17 17:38
@scannillo Thanks for news!

**Comment by sestevens** [comment] 2020-12-01 21:18
👋  Hi everyone,

We just released a [beta version](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of the SDK that includes partial Swift Package Manager support. Please try it out and open a GitHub issue if you have any feedback!

Resources:
- [SPM integration instructions](https://github.com/braintree/braintree_ios/tree/5.0.0-beta1#swift-package-manager-v5-beta)
- [Version 5 migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0-beta1/V5_MIGRATION.md)

Thanks,
Braintree SDK Team

**Comment by francybiga** [comment] 2021-01-07 11:25
Hi, when could be expect SPM support for the `braintree-ios-drop-in` SDK?

**Comment by scannillo** [comment] 2021-01-07 15:00
Hello @francybiga - SPM support for Drop-in is actively in development. You can stay tuned about it in the corresponding [GitHub issue.](https://github.com/braintree/braintree-ios-drop-in/issues/155)

**Comment by eseay** [comment] 2021-01-14 15:20
Hey @scannillo - do you have any idea what the timeline for going from v5.0 Beta to v5.0 GM looks like? My team is generally averse to shipping things marked "Beta" into production, but we're at the same time quite eager to move this dependency out of Carthage and into SPM. If the "Beta" tag is there simply for the purposes of dependency management/version resolution stuff and the code is indeed ready for production use, however, just let me know. Thanks!

**Comment by sestevens** [comment] 2021-02-11 17:41
Support for Swift Package Manager has been added in [version 5.0.0](https://github.com/braintree/braintree_ios/releases/tag/5.0.0). See our [Swift Package Manager guide](https://github.com/braintree/braintree_ios/blob/5.0.0/SWIFT_PACKAGE_MANAGER.md) for instructions and required workarounds.

Also, please see our [migration guide](https://github.com/braintree/braintree_ios/blob/5.0.0/V5_MIGRATION.md) for steps to upgrade your integration.

**Closed by sestevens** 2021-02-11 17:41 UTC
Labels: enhancement, fixed in beta

**Comment by aymenafia** [comment] 2021-02-15 11:42
Hi,
import PPRiskMagnes is not found when i create archive, in the version 5.0.0 when i added brainTree by  Swift Package Manager.

**Comment by sestevens** [comment] 2021-02-16 16:16
@aymenafia Did you follow the instructions in our [Swift Package Manager guide](https://github.com/braintree/braintree_ios/blob/master/SWIFT_PACKAGE_MANAGER.md#binary-dependencies) about explicitly including binary dependencies (such as `PPRiskMagnes`)? You'll need to check the box for `PPRiskMagnes` when adding the Braintree frameworks to your project via Swift Package Manager.

If this doesn't resolve the problem, please open a new GitHub Issue with more details. Thanks!

**Comment by mbuchetics** [comment] 2021-02-24 08:48
Is there any ETA when `CardinalMobile.framework` will be available via SPM and/or XCFramework as well? From what I can tell, there is currently no Apple Silicon Simulator support and it's the last remaining `.framework` in my project.

**Comment by sestevens** [comment] 2021-02-24 15:15
@mbuchetics Sorry, we don't have an ETA for an CardinalMobile `.xcframework` at this point. We know folks are eager to migrate fully to SPM and that our current workarounds are less than ideal. 

You're correct that Cardinal's current `.framework` doesn't work on Apple Silicon simulators. We've requested both an `.xcframework` and a `.framework` with support for Apple Silicon simulators, and as soon as we receive one or both, we'll update the Braintree SDK as quickly as possible.

**Comment by sestevens** [comment] 2021-03-18 18:12
@mbuchetics We just received an xcframework from CardinalMobile today. We'll do our best to get a release for this our soon, but in the meantime you can check out the branch [`cardinal-xcframework`](https://github.com/braintree/braintree_ios/tree/cardinal-xcframework) or take a look at PR #649.

**Comment by sestevens** [comment] 2021-03-18 18:18
Unfortunately, CardinalMobile's xcframework doesn't appear to have support for Apple Silicon Simulators. We'll follow up with them on that.

**Comment by scannillo** [comment] 2021-03-23 16:37
Hello @mbuchetics - we just released [v5.3.0 of the Braintree iOS SDK](https://github.com/braintree/braintree_ios/releases/tag/5.3.0), which includes an xcframework for CardinalMobile. The integration steps for `BraintreeThreeDSecure` via SPM have been simplified, please see the instructions [here](https://github.com/braintree/braintree_ios/blob/master/SWIFT_PACKAGE_MANAGER.md#versions-530).
