### ISSUE TITLE
Return to Merchant button shows after Paypal sandbox login

### ISSUE THREAD

**Issue by V1992** [braintree/braintree_ios#381] opened 2018-01-16 10:23 UTC
### General information

* SDK/Library version: iOS V4
* Environment: Sandbox
* iOS Version and Device:  iOS 11.0 on iPad mini

### Issue description

From Dropdown UI, when I tap on the Paypal it redirects to the paypal sanbox account page. And after successful login it just shows a "**Return to merchant**" button (the current url page where this button shows  **https://www.sandbox.paypal.com/checkoutnow?nolegacy=1&token=EC-7HE35921NK4087147&bt_int_type=2#/checkout/genericError?code=SU5WQUxJRF9SRVNPVVJDRV9JRA%3D%3D**). When click on it, then it go back to the app dropdown UI page. And then this will check the if condition _result.paymentOptionType_  and  **requestOneTimePayment:request** method gets called. The variables tokenizedPayPalAccount and error are nil when checked.

              if(result.paymentOptionType == BTUIKPaymentOptionTypePayPal){
        
                self.braintreeClient = [[BTAPIClient alloc] initWithAuthorization:_tokenizationKey];
                BTPayPalDriver *payPalDriver = [[BTPayPalDriver alloc] initWithAPIClient:self.braintreeClient];
                payPalDriver.viewControllerPresentingDelegate = self;
                payPalDriver.appSwitchDelegate = self; // Optional
                // Specify the transaction amount here. "2.32" is used in this example.
                BTPayPalRequest *request= [[BTPayPalRequest alloc] initWithAmount:@"2.32"];
                request.currencyCode = @"USD"; // Optional; see BTPayPalRequest.h for other options
                
                [payPalDriver requestOneTimePayment:request completion:^(BTPayPalAccountNonce * _Nullable tokenizedPayPalAccount, NSError * _Nullable error) {
                    if (tokenizedPayPalAccount) {
                        NSLog(@"Got a nonce: %@", tokenizedPayPalAccount.nonce);

                        // Access additional information
                        NSString *email = tokenizedPayPalAccount.email;
                        NSString *firstName = tokenizedPayPalAccount.firstName;
                        NSString *lastName = tokenizedPayPalAccount.lastName;
                        NSString *phone = tokenizedPayPalAccount.phone;

                        // See BTPostalAddress.h for details
                        BTPostalAddress *billingAddress = tokenizedPayPalAccount.billingAddress;
                        BTPostalAddress *shippingAddress = tokenizedPayPalAccount.shippingAddress;
                    } else if (error) {
                        // Handle error here...
                    } else {
                        // Buyer canceled payment approval
                    }
                }];

Payment page not showing after login. This is the issue

Thanks in advance

**Comment by bluk** [comment] 2018-01-16 17:07
I assume you're trying to use the [Braintree iOS v5 Dropin](https://github.com/braintree/braintree-ios-drop-in). It seems you are mixing the iOS Drop-in code with the custom PayPal request code for one-time checkout. Drop-in supports the [vaulted PayPal flow](https://developers.braintreepayments.com/guides/paypal/overview/ios/v4). You should only need to use code [like in the README](https://github.com/braintree/braintree-ios-drop-in#show-drop-in) to show and get the result from Drop-in.

You can then get the `result.paymentMethod.nonce` or cast the `result.paymentMethod` to the corresponding nonce type such as `BTPayPalAccountNonce` to get the details. Something like:

```
    BTDropInController *dropIn = [[BTDropInController alloc] initWithAuthorization:self.authorizationString request:dropInRequest handler:^(BTDropInController * _Nonnull dropInController, BTDropInResult * _Nullable result, NSError * _Nullable error) {
        if (error) {
            self.progressBlock([NSString stringWithFormat:@"Error: %@", error.localizedDescription]);
            NSLog(@"Error: %@", error);
        } else if (result.isCancelled) {
            NSLog(@"Cancelled");
        } else {
            if (result.paymentOptionType == BTUIKPaymentOptionTypePayPal) {
                BTPayPalAccountNonce *paypalNonce = (BTPayPalAccountNonce *)result.paymentMethod;
                NSLog(@"%@", paypalNonce.nonce);
                NSLog(@"%@", paypalNonce.email);
            }
        }
        [dropInController dismissViewControllerAnimated:YES completion:nil];
    }];
```

**Comment by bluk** [comment] 2018-01-16 19:52
Closing this as a duplicate of https://github.com/braintree/braintree-ios-drop-in/issues/74

**Closed by bluk** 2018-01-16 19:52 UTC

**Comment by V1992** [comment] 2018-01-17 06:56
I added the new vault code that you mentioned above by replacing it with one-time checkout code. But still "Return to merchant" button displaying after login. This is the url page **https://www.sandbox.paypal.com/agreements/approve?nolegacy=1&ba_token=BA-4M46965845473361C&bt_int_type=2#/checkout/genericError?code=VU5TVVBQT1JURURfUEFZRUVfQ1VSUkVOQ1k%3D**

Only this was missing before in the plist.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>com.projectname.payments</string>
	<string>com.paypal.ppclient.touch.v1</string>
	<string>com.paypal.ppclient.touch.v2</string>
	<string>com.paypal.ppclient.touch.v3</string>
	<string>org-appextension-feature-password-management</string>
</array>
</plist>

Now added the same. 
But still payment page not showing.

**Comment by bluk** [comment] 2018-01-17 16:18
It appears that your PayPal merchant account may not be setup correctly in sandbox. You should contact [Braintree Support](https://developers.braintreepayments.com/forms/contact) who can help verify that your settings are correct.
