### ISSUE TITLE
EXC_BAD_ACCESS KERN_INVALID_ADDRESS crashes 

### ISSUE THREAD

**Issue by JavierSilvaFreeNow** [braintree/braintree_ios#584] opened 2021-01-18 14:59 UTC
**Integration Details:**
 - SDK/Library Version: 4.36.1
 - Environment: Production
 - iOS Version: iOS 12.0-14.0
 - Integration type & version: CocoaPods 1.8.4

**Describe the bug**
Hey everyone, I was approached by our analytics department due to a couple of crashes reported through the Crashlytics tool related to the Braintree SDK, fortunately they don't seem to be affecting a high percentage of our user base but we thought it was a good idea to report them regardless.

Some background: we recently implemented our PSD2 SCA compliance strategy using the 3DSv2 solution offered by your product, which means these crashes are the result of active users attempting to make a purchase through our app and getting routed through the SDK for an SCA challenge.

**Crashed: com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010**
+[BTThreeDSecureAuthenticateJWT authenticateJWT:withAPIClient:forLookupResult:success:failure:]
-[BTThreeDSecureV2Provider cardinalSession:stepUpDidValidateWithResponse:serverJWT:] + 432
-[CardinalSession sendValidationResponse:andJWT:] + 536
-[CardinalSession stepUpUserInputWithResponseData:]_block_invoke + 1408

**Crashed: com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010**
-[BTThreeDSecureV2Provider callFailureHandlerWithErrorDomain:errorCode:errorUserInfo:failureHandler:] + 136
-[BTThreeDSecureV2Provider cardinalSession:stepUpDidValidateWithResponse:serverJWT:] + 696
-[CardinalSession sendValidationResponse:andJWT:] + 536
-[CardinalSession stepUpUserInputWithResponseData:]_block_invoke + 324

We did not encounter any hard crashes during our implementation process, which makes the issues hard to reproduce.

Please let me know if you need any more info. Thank you for your time.

**Comment by sestevens** [comment] 2021-01-22 16:05
@JavierSilvaFreeNow Thanks for reporting this! We'll take a look and post any findings here.

**Comment by scannillo** [comment] 2021-04-06 20:44
Hi @JavierSilvaFreeNow - we've reached out to our MPI provider (CardinalMobile) and reported this crash to them. Since there are no steps to reproduce, we are going to close this issue. 

Please comment or open a new issue if you get more information on replicating this crash.

**Closed by scannillo** 2021-04-06 20:44 UTC

**Comment by JavierSilvaFreeNow** [comment] 2021-07-12 06:15
Hey guys,

I was wondering if you got any updates from Cardinal on this issue, we got reports of this crash being among the top 5 affecting our app at the moment.

As far as new information, we found out that the crash itself happens on the app's background thread (com.apple.root.background-qos) but we're still unlucky on replicating it.

Thank you.

**Comment by scannillo** [comment] 2021-07-20 16:29
👋  Hi @JavierSilvaFreeNow - we haven't heard any updates from Cardinal. I just poked them to get an update and will keep you posted if any additional info comes about.
