### ISSUE TITLE
Blank auth view shown if card not enrolled in 3D secure

### ISSUE THREAD

**Issue by kierobinson1** [braintree/braintree_ios#320] opened 2017-03-24 14:28 UTC
#### Developer Info

- Braintree SDK version: 4.7.5

- Integration type and version: CocoaPods 1.2.0

- Environment: Production

#### Issue Details
We are noticing some strange behaviour when using `BTThreeDSecureDriver` to manually verify a card and pop up the `BTThreeDSecureAuthenticationViewController` (we're using the `verifyCardWithNonce` function as we need to verify both vaulted and new cards).

 If a card isn't enrolled in ThreeDSecure, it will show a blank `BTThreeDSecureAuthenticationViewController` which has no content within it, and shows only a cancel button on the navbar. It dismisses as soon as it's loaded, which could be quite confusing to the user. Ideally, this wouldn't be shown unless the card is enrolled in 3DS, but we don't seem to know this information until the `verifyCard` completion handler is called, in which we can access the `card.liabilityShiftPossible` Bool.

**Comment by demerino** [comment] 2017-03-24 21:12
@kierobinson1 Thanks again raising these issues. `verifyCardWithNonce` shouldn't require checks on your part - I wonder if the issue is with the `requiresUserAuthentication` check?

https://github.com/braintree/braintree_ios/blob/master/Braintree3DSecure/BTThreeDSecureLookupResult.m#L6

Maybe you can put a breakpoint there and see if there is a URL (maybe it is an empty string) and some sort of behavior has changed.

**Comment by kierobinson1** [comment] 2017-03-27 12:48
@demerino I've just had a look using a breakpoint, and the URL seems to be valid, the same as a card with 3DS enabled. Are there any other places that could be used to check if the user has enrolled in 3DS?

**Comment by demerino** [comment] 2017-03-27 17:45
If a card is not enrolled - this check will bypass the authorization. In my production tests, when using a card that isn't enrolled, the verification popup is not presented. I'll need to work on recreating the issue along with verifying the behavior with our product team. I'll update with my findings.

**Comment by demerino** [comment] 2017-03-30 19:34
Quick question - does this issue occur on <= iOS9 devices?

**Comment by kierobinson1** [comment] 2017-03-31 19:35
Hi @demerino , just had a look now and this does happen on iOS 9, we can't test any lower versions than that as we don't use the drop-in pre iOS 9. Have you managed to replicate it?

Cheers

**Comment by demerino** [comment] 2017-03-31 21:30
No, I have not been able to. If you have time - could you do a quick test in a vanilla app (make a new app and just use drop-in) to see if this issue still occurs? 

OR

When I used the test card `4000000000000051` (*Not Enrolled*) it does not present the modal for me. What does it do for you in sandbox mode?

**Comment by meismyles** [comment] 2017-04-05 15:03
The card this is occurring on is a pre-paid Mastercard (for a new tech bank called Monzo that isn't actually a bank as of yet). The card seems to operate exactly as a debit card would, but as it isn't an actual account it has no account number, sort code, etc. Basically it works exactly as a travel card would.

I'm wondering if the issue is to do with this? Maybe Monzo kind of half support 3D secure in a way that it seems to be enabled but don't require any checks? Or maybe something else?

**Comment by demerino** [comment] 2017-04-05 16:02
That makes WAY more sense. I would contact Braintree support and ask them about support for that type of card. I'll close this issue for now.

**Closed by demerino** 2017-04-05 16:02 UTC
