### ISSUE TITLE
PKPaymentAuthorizationControllerExportedObject authorizationDidFinishWithError

### ISSUE THREAD

**Issue by janhalousek** [braintree/braintree_ios#117] opened 2015-04-18 12:03 UTC
Hi,

I am seeing objc_msgSend crash in `[PKPaymentAuthorizationControllerExportedObject authorizationDidFinishWithError:]` occurring on production.
Seems like the crash comes after successful `BTPaymentMethod` creation, just moments after dismissing `PKPaymentAuthorizationViewController`.
The flow is integrated using `BTPaymentProvider`.

Do you have any similar issues, or any idea how to prevent this from happening? 
Thanks

**Comment by mickeyreiss** [comment] 2015-04-19 14:35
Hi! Are you seeing this in development or via crash reports in production? Any correlation with iOS base SDK version or runtime version?

We've been seeing reports of this issue intermittently but have not been able to narrow it down between our sdk's usage of PassKit and PassKit itself.

**Comment by janhalousek** [comment] 2015-04-19 19:31
Hi, 
thanks for your reply. We see it only in reports from production, no correlation with iOS versions, failing on 8.1, 8.2 and 8.3.

I understand, please keep me updated if anything new arises.

We might consider implementing the flow via direct use of PassKit. If we do, I'll let you know if any correlation arises.

**Comment by mickeyreiss** [comment] 2015-04-20 18:49
We're curious to find out how that goes! Feel free to re-open this issue if our usage of the PassKit APIs is at fault for the crasher.

**Comment by chamarapaul** [comment] 2015-04-28 17:58
I'm seeing this issue in my production crash logs as well, and I'm using the PassKit integration style documented here: https://developers.braintreepayments.com/ios+ruby/guides/apple-pay/client-side

There are a couple of Apple bug reports filed too:
http://www.openradar.appspot.com/19767271
https://openradar.appspot.com/20189448

Maybe reopen this issue? Let me know if I can provide more info (logs, etc.)

**Comment by burnto** [comment] 2015-04-28 18:13
Thanks @chamarapaul. 

The Apple bug reports do further indicate that this is likely a PassKit bug. I'm fine re-opening to indicate that we believe resolution is waiting on PassKit.

@janhalousek are you still seeing this issue with the direct PassKit usage?

**Comment by janhalousek** [comment] 2015-05-03 08:40
@burnto Unfortunately we don't use the direct PassKit integration yet.. I'll keep you informed in case we do

**Comment by glentregoning** [comment] 2015-07-09 00:09
FYI I opened a radar for this an it was marked as a duplicate by Apple which indicates to me this is an Apple Issue. See http://www.openradar.appspot.com/19767271

**Comment by mthole** [comment] 2015-07-09 18:01
I discussed this error with Apple engineers at the WWDC Labs. They confirmed that it was indeed an Apple issue, and that it should be fixed in iOS 9. I don't expect it in an 8.x, unfortunately.

**Comment by mthole** [comment] 2015-07-09 18:03
I was able to (fairly grossly) work around this issue by explicitly *leaking* the `PKPaymentAuthorizationViewController` once I was done with it. If you do so, make sure you clear out the `delegate` too.

**Comment by burnto** [comment] 2015-08-05 15:41
Since we have some evidence this is an Apple issue, I'm closing this. Thanks everyone for reporting and helping us figure this out.

**Closed by burnto** 2015-08-05 15:41 UTC

**Comment by mobitar** [comment] 2015-08-10 16:24
@mthole what do you mean by explicitly leaking? Did you go into the Braintree framework itself and modify the source?
