### ISSUE TITLE
[PayPal] Ability to detect when tokenizePayPalAccountWithPayPalRequest method about to show the Paypal web page. 

### ISSUE THREAD

**Issue by siddarth-byte** [braintree/braintree_ios#773] opened 2022-01-04 14:38 UTC
**Is your feature request related to a problem? Please describe.**

`BTAppSwitchDelegate` was removed in v5.  Earlier it was used to receive lifecycle notifications about the progress of PayPal payments, in case if  app needs to update some UI in response. It takes a few seconds between calling `tokenizePayPalAccountWithPayPalRequest` and then showing the PayPal web page/Safari VC. If we want to show a loader during that time, Is there another alternative for `BTAppSwitchDelegate` now?
https://github.com/braintree/braintree_ios/blob/master/V5_MIGRATION.md

The migration doc suggested using `BTViewControllerPresentingDelegate` instead but that doesn't make sense in the case of PayPal as it usages `ASWebAuthenticationSession` on iOS 12+, and `BTViewControllerPresentingDelegate` methods will not be invoked in that case.  

**Describe the solution you'd like**

There should be a delegate that SDK consumers can implement to know when SDK is about to show a PayPal web page. Eg. 
As `appContextWillSwitch` was used earlier for the same. 

Also I wanted to highlight that `BTAppSwitchDelegate` has been suggested in past as well for the same purpose. 
eg. https://github.com/braintree/braintree_ios/issues/383 https://github.com/braintree/braintree_ios/issues/549

**Comment by sshropshire** [comment] 2022-01-04 16:14
Hi @siddarth-byte thanks for using the Braintree SDK for iOS. Can you show the loading indicator right before calling `tokenizePayPalAccount`? This would have the same effect.

As a side note, we no longer perform an app switch in this scenario, so the delegate was removed from our SDK.

**Comment by siddarth-byte** [comment] 2022-01-04 17:10
@sshropshire  I want to show a full screen loader so yes I can call it before `tokenizePayPalAccount` but then I would like to hide it once `tokenizePayPalAccount` opens the Paypal web page so that loader shouldn't obstruct user from interacting with the web page for the authentication.

**Comment by sshropshire** [comment] 2022-01-05 21:35
@siddarth-byte `ASWebAuthenticationSession` does have a modal presentation style. You should be able to show the loader right before calling `tokenizePayPalAccount` in the presenting `UIViewController` and hide it after successful tokenization.

**Comment by sshropshire** [comment] 2022-01-05 21:37
@siddarth-byte also if I'm misunderstanding your request, a video of your current implementation will help us to understand the overall use case.

**Comment by siddarth-byte** [comment] 2022-01-06 06:38
@sshropshire I am using a fullscreen loader viewcontroller and would like to dismiss it once ASWebAuthenticationSession presents safari VC. Here is a video reference with SDK4.x, as we are still analysing v5.0 migration. The similar issue has been discussed before here https://github.com/braintree/braintree_ios/issues/246 

https://user-images.githubusercontent.com/72494224/148339956-516f2823-23bb-462a-9cb1-0de57a12027d.MP4

**Comment by sshropshire** [comment] 2022-01-06 19:36
@siddarth-byte I see that's the expected behavior. Is the v5 integration in a working state so we could see the actual behavior you're experiencing?

**Comment by siddarth-byte** [comment] 2022-01-07 03:27
@sshropshire Yes, the above video is expected behaviour with SDK 4.x since I am hiding the full-screen loader `viewcontroller` on the `appContextWillSwitch` method in the above case. If I don't hide it, then that leads to unexpected behaviour. For example, on iOS 12.0, we have seen the PayPal blank page bug where the app needs to dismiss any presenting view controller (Eg. Loading VC) before presenting SFSafariController (which is done internally by PayPal SDK) to fix the same. Please refer to the video attached below for iOS 12.0 bug. 

https://user-images.githubusercontent.com/72494224/148485493-41f1a556-0542-448e-9069-d2b857b35d9a.mp4

The tokenisation completes once a user completes the authentication in safari VC, but I need to hide the loading `viewcontroller` before safari VC is about to present on the screen. The solution you suggested above to hide tokenisation completion will not work here and might lead to unexpected UI bugs. We will avoid V5 migration until we resolve all known issues. So yeah, I don't have any video experience with V5.0  yet.

**Comment by siddarth-byte** [comment] 2022-01-14 18:56
@sshropshire Any updates here?

**Comment by jaxdesmarais** [comment] 2022-01-18 23:30
Hello @siddarth-byte -

Currently there is not a delegate method for this function as the VC will always present on top of the loading indicator and could then be dismissed when you call `tokenizePayPalAccountWithPayPalRequest` as Steven mentioned. I was able to do some testing on my end and the loading indicator did not block the view controller as you had mentioned previously.

Is the reason to have this dismissed between button click and alert presentation to handle cases like you mentioned where the screen is blank? If so, that's certainly not the expected behavior - are you able to provide steps to reproduce that bug?

**Comment by siddarth-byte** [comment] 2022-01-19 11:10
@jaxdesmarais   Did you try this on iOS 12? If not can you try on the same? 
We have found the blank page issue with iOS 12 only.

**Comment by jaxdesmarais** [comment] 2022-01-19 22:28
Hello @siddarth-byte -

Thanks for reaching back out with those details. I ran ~10 tests on iOS 12 but am unable to replicate the blank screen issue you are seeing. This was tested on XCode 12.5 using an iPhone 8 running iOS 12 in simulator. Are you able to provide a small sample app that we can take a look at to replicate this error? Or any other steps I should be using to replicate? My tests included adding a loading indicator and removing it in my `tokenizePayPalAccountWithPayPalRequest` function.

**Comment by siddarth-byte** [comment] 2022-01-25 11:52
@jaxdesmarais  We have recently dropped support for iOS 12 hence Its not a blocker for us to upgrade to latest version. You can close this ticket now.

**Comment by jaxdesmarais** [comment] 2022-01-25 15:31
Hello @siddarth-byte -

Thanks for the update. I'll go ahead and close this issue, but if you run into any other issues please feel free to reach back out.

**Closed by jaxdesmarais** 2022-01-25 15:31 UTC
