### ISSUE TITLE
BTPayPalAccountNonce phone property is nil

### ISSUE THREAD

**Issue by dsmailes** [braintree/braintree_ios#784] opened 2022-01-26 12:27 UTC
- Braintree SDK Version: 5.4.4 (also tested with 5.6.1)
 - Environment: Sandbox
 - iOS Version: iOS 15.2
 - Xcode Version: 13.2.1
 - Device: iPhone 13 Pro / iPhone 8 simulator
 - Integration type & version: SPM 5.6.1
 - Development Processor Type: Apple Silicon M1

**Describe the bug**
The phone property of `BTPayPalAccountNonce` returns as `nil` even though the sandbox accounts being used have a phone number.

**To Reproduce**
Tokenise a sandbox PayPal account with `BTPayPalDriver` and `BTPayPalCheckoutRequest`
Attempt to access the`.phone` property of the returned `BTPayPalAccountNonce`

**Expected behavior**
The phone property should contain the phone number of the account.

Code:

```
guard let braintreeClient = BTAPIClient(authorization: token.token) else {
                    completion(.failure(BookingErrors.paypalCommunicationError))
                    return
                }

                let paypalDriver = BTPayPalDriver(apiClient: braintreeClient)
                let request = BTPayPalCheckoutRequest(amount: "\(totalCost)")

                paypalDriver.tokenizePayPalAccount(with: request) { (account, error) in
                    if let error = error {
                        completion(.failure(error))
                        return
                    }

                    let credentials = PayPalExpressCredentials(
                        nonce: account?.nonce ?? "",
                        email: account?.email ?? "",
                        phone: account?.phone ?? ""
                    )
                    completion(.success(credentials))

```

**Comment by jaxdesmarais** [comment] 2022-01-26 14:49
Hello @dsmailes -

Thanks so much for reporting this issue. I have been able to reproduce this in production as well. I will investigate and keep you posted when we have more details.

**Comment by jaxdesmarais** [comment] 2022-01-26 23:07
👋  @dsmailes - our teams have identified and are working to resolve this issue. We will reach back out once this is fully resolved.

**Comment by dsmailes** [comment] 2022-01-27 07:27
@jaxdesmarais - thanks so much for getting onto this so quickly. Looking forward to the update! Anything we can help with re: testing?

**Comment by yburadkar** [comment] 2022-01-28 13:49
@jaxdesmarais Thanks a lot for a quick response from the Braintree team on this issue. I work with @dsmailes on the same project and am seeing the same issue with the Braintree Android SDK (v4.6.0) where the `PayPalAccountNonce` returns an empty string for the `phone` property.

Just wanted to confirm if the planned resolution for this issue will be available as a new SDK version or would this be a backend fix that would resolve the issue on both platforms without any SDK updates on the clients? Please let me know if you would like me to raise it as separate issue for the Android SDK.

**Comment by yburadkar** [comment] 2022-01-28 14:37
Nice. Thank you for the prompt update once again. @jaxdesmarais 👍

**Comment by yburadkar** [comment] 2022-02-15 20:55
Hi @jaxdesmarais I see that this issue is still open. Just wanted to check if you have any updates on the fix.

**Comment by jaxdesmarais** [comment] 2022-02-16 17:37
Hello @yburadkar - our internal teams are still investigating a fix for this issue and we have been actively following along to ensure once a solution is provided we are able to provide an update on the fix. As soon as we have more details or next steps, I will be sure to reach back out. Thanks for your patience.

**Comment by yburadkar** [comment] 2022-02-16 18:15
@jaxdesmarais Thank you for the update. Hope to hear back from you soon.

**Comment by jaxdesmarais** [comment] 2022-03-24 17:13
Hello @yburadkar and @dsmailes -

Apologies for the long delay on this. I was able to hear back from our internal team and they noted that there is a toggle to enable receiving the phone number. Because it is sensitive customer data, you have to opt-in to receiving it. You can enable it by following these steps:

1. Log into the Business Manager for your account. Sandbox URL: https://www.sandbox.paypal.com/mep/dashboard and Production: https://www.paypal.com/mep/dashboard
2. Hover over your name on the top right and click on "Account Settings"
3. Towards the bottom you will see a Products & Services section where you will click on "Website Payments"
4. Click on "update" next to Website preferences
5. Under Contact telephone number you will want to select either on - optional or on - mandatory

If it is optional and a customer does not provide their phone number, you would not receive one in the response. Once the toggle is enabled it may take up to 2 hours to begin receiving the phone number data. I was able to test this on my end and we are now seeing the phone number as expected, but please let me know if you run into issues.

**Comment by dsmailes** [comment] 2022-03-25 07:48
@jaxdesmarais thank you for the update, it is much appreciated!

**Comment by jaxdesmarais** [comment] 2022-03-25 13:59
You are welcome, @dsmailes! I am going to close this issue as from our testing the above should resolve this, that said, if you continue to run into issues with this, please don't hesitate to reach back out and we'd be happy to investigate further. 🚀

**Closed by jaxdesmarais** 2022-03-25 13:59 UTC
