### ISSUE TITLE
Incorrect parameter description.

### ISSUE THREAD

**Issue by BenMaer** [braintree/braintree_ios#261] opened 2016-09-08 22:41 UTC
In `BTDropInViewController.h`, the following method is offered:
```
- (void)setCardExpirationMonth:(NSInteger)expirationMonth year:(NSInteger)expirationYear;
```

Part of the description says

> /// @param expirationYear The expiration year as a four-digit number.

I tried passing through a 4 digit number (`2018` from your test card information), but the pay button was disabled in the `BTDropInViewController` instance, even though it displayed the correct date information. I had to set it to the latter 2 digits `18`, which works. Note that I still see 2018 in the `BTDropInViewController` instance when passing just `18` as a parameter.

**Comment by sdcoffey** [comment] 2016-09-08 23:06
Hey @BenMaer, 

Thanks for the heads up! Taking a look at this.

**Comment by BenMaer** [comment] 2016-09-08 23:07
@sdcoffey 
After further investigation, I realize that the issue happens also sometimes happens when passing in just a two-digit number. I suspect this issue is not with the description, but with the code itself. Most of the times the pay button is enabled immediately when the view is up, but sometimes it is not.

**Comment by sdcoffey** [comment] 2016-09-08 23:21
@BenMaer would you mind posting a code snippet? Are you setting all fields ahead of time and finding that the call-to-action button is disabled?

**Comment by BenMaer** [comment] 2016-09-08 23:48
@sdcoffey 
Sure, here is what I'm doing. Note that my classes are prefixed with `DR`, and that `kDRConfirmPurchaseDealViewController_enableTestCardInformation` is a macro currently set to `1`.

```
-(void)BTDropInViewController_show_forConfirmPurchase
{
	BTDropInViewController* const dropInViewController =
	[[BTDropInViewController alloc]initWithAPIClient:[DRBTAPIClient sharedInstance].apiClient];
	[dropInViewController setDelegate:self];
	
#if kDRConfirmPurchaseDealViewController_enableTestCardInformation
	[dropInViewController setCardNumber:@"4111111111111111"];
	[dropInViewController setCardExpirationMonth:12 year:18];
#endif

	DRGenericModalNavigationController* const genericModalNavigationController = [[DRGenericModalNavigationController alloc]initWithRootViewController:dropInViewController];

	[self presentViewController:genericModalNavigationController animated:YES completion:nil];
}
```

**Comment by sdcoffey** [comment] 2016-09-09 00:13
Ah got it. Yeah so you were right that it's actually an issue in the application code. Looks like a race condition, I'm able to reproduce it pretty reliably using the network link conditioner and simulating a high latency network. Again, thanks for letting us know, I'll put this in the queue and close this issue when it's been fixed.

**Comment by sdcoffey** [comment] 2016-09-09 00:25
The temporary workaround here is to implement the delegate method `dropInViewControllerDidLoad:`, and set those properties there, as that method will get called after the dependent network call completes.

**Comment by BenMaer** [comment] 2016-09-09 01:42
Thanks @sdcoffey ! Especially for being so responsive. I'll implement that tomorrow and let you know if there's any issue.

**Comment by demerino** [comment] 2016-10-20 17:53
Closing due to inactivity. Feel free to reopen or create a new issue if the problem persists.

**Closed by demerino** 2016-10-20 17:53 UTC
