### ISSUE TITLE
Request to make more UI headers public.

### ISSUE THREAD

**Issue by darronschall** [braintree/braintree_ios#225] opened 2016-02-19 15:27 UTC
I have a custom "add credit card" form that used headers from the 3.x release that are no longer public in 4.x. 

Is there any chance you can make these headers public again in an upcoming release? 

```
#import "BTUIUtil.h"
#import "BTUICardType.h"
#import "BTUILocalizedString.h"
#import "BTUIViewUtil.h"
#import "BTUICardExpirationValidator.h"
#import "BTUICardExpiryFormat.h"
```

I do not want to use the drop-in UI because the design and functionality is not consistent with my app, but I also do not want to reinvent the wheel and roll my own validation. The card type, card hint, and validations are very helpful outside of the drop-in context.

My epic workaround was to modify the BraintreeUI.h header to include the additional headers that I leverage in my custom form. Then, in the Pod project I changed the individual headers from "Project" to "Public".

**Comment by skunkworks** [comment] 2016-02-19 17:46
@darronschall Absolutely! Sorry that we didn't expose these publicly earlier. Your feedback is really helpful to us to figure out how people are using our product. I'll try to get this into the next release.

**Comment by burnto** [comment] 2016-02-19 18:00
@skunkworks I'm all for offering as much as we can here, but I'm not sure we want to add these to our public SDK API.

Anything we offer in the public API must remain backward compatible for the remainder of this major version. So if we have any intention to redo internals, this will constrain those efforts.

Let's at least consider the pros and cons here. It's possible we want to break out the specs/versioning for components like this to make it easier for us to independently bump versions when we need to introduce breaking changes.

**Comment by skunkworks** [comment] 2016-02-19 18:08
Hm, it is a good point that an overhaul of the UI code will require a major version bump. It feels like the UI code might be better off with a separate podspec.

Sorry @darronschall, I don't think I'll be able to get this into the next release.

**Comment by darronschall** [comment] 2016-02-19 19:14
Thanks for considering this request!

I have a workaround for now, so any action is not urgent (and it's only mildly annoying having to manually update this after every `pod update` call). This is completely a quality-of-life issue for me.

I like @burnto's suggestion! My preference would be to expose these "do it yourself helpers" as a separate UI-Util spec that I can pull in. Then Drop-In can make any changes it wants to internally...

**Comment by lupugabriel** [comment] 2016-03-15 12:22
@darronschall can you tell me exactly how you made those classes public? i still have this issue. thanks.

**Comment by darronschall** [comment] 2016-03-15 12:46
@lupugabriel I use Cocoapods. 

1. In the Pods project in your workspace, expand the Pods -> Braintree -> UI folder.
1. Edit the BraintreeUI.h header file. At the bottom of the file, list the imports that you need (I needed all of the ones I mentioned in my original comment).
1. For every header added to the  BraintreeUI.h file: Select the header file, then in the File Inspector in Xcode, change the Target Membership. Next to the Braintree target you'll see Project. Expand the drop down and select Public instead.

After that, you'll be able to compile/run and leverage the headers.

Note that every time you `pod install` you'll need to repeat this process.

**Comment by filipandrei87** [comment] 2016-05-23 14:44
+1 for the request as I'm having the same issue after upgrading the library
@darronschall thanks for the workaround

**Comment by skunkworks** [comment] 2016-05-23 22:35
We will be taking a look at this shortly, thanks for your patience.

**Comment by demerino** [comment] 2016-07-15 21:53
Take a look at `4.4.0`+. We've added a new Drop-In component and exposed our UI components (along with styling). More info [here](https://github.com/braintree/braintree_ios/blob/master/Docs/Drop-In-Update.md).

The new `BraintreeUIKit` framework is what you're looking for! If you have more suggestions or requests, let us know by opening a new issue.

**Comment by darronschall** [comment] 2016-07-19 19:00
Thanks for this! I tried to use the new `BraintreeUIKit` but ran into two issues:

1) I still had to apply my previous workaround in order to make `BTUIKCardExpiryFormat.h` and `BTUIKCardExpirationValidator.h` both public.

2) My project stopped linking when I added the `Braintree/BraintreeUIKit` pod. The dreaded undefined symbols linking error: `Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BTUIKViewUtil", referenced from:` ... for every BraintreeUIKit class I was using. I tried to troubleshoot this for a couple hours but wasn't able to find the right sacrificial lamb to offer unto Xcode's altar to appease it. I have since given up and reverted back to my previous state.

I'll also note that the docs for https://github.com/braintree/braintree_ios/blob/master/Docs/Drop-In-Update.md#braintreeuikit are slightly wrong. The pod is `Braintree/BraintreeUIKit`, but the doc specifies `Braintree/UIKit`.

**Comment by demerino** [comment] 2016-07-19 21:23
Thanks a ton for the feedback @darronschall 

We'll look into all of these issues and making those headers public as well. 

I was wondering what version of `Cocoapods` you are using. Have you bumped up to `1.x`? It might be useful to blow away your `/Pods` folder too (along with cleaning build folders, etc...). Any other information about your setup could be useful in debugging (Swift? ObjC? iOS Target?). We're not seeing this issue in our current tests.

**Comment by darronschall** [comment] 2016-07-21 14:15
Thanks @demerino. I'm using Cocoapods 1.0.1. I deleted the Pods project and started over, but I'm still getting the same `undefined symbols` linking errors but only for the BTUIK* classes.

I'm using the following in my Podfile:

```ruby
pod 'Braintree/Card', '4.4.0'
pod 'Braintree/BraintreeUIKit', '4.4.0'
pod 'Braintree/DataCollector', '4.4.0'
```

This is part of a hybrid Objective-C and Swift project. For what it's worth, I don't get any linking errors if I downgrade and manually expose the headers I need.

The only change I made in upgrading was replacing the `UI` subspec (that I was using the headers from) with `BraintreeUIKit` instead, and bumping from version 4.1.2 to 4.4.0. I did manually modify the Braintree project to expose those two additional headers that I needed, and, of course, migrating class names from BTUI* to BTUIK*.

Given the above, the problem _seems_ to be in the BraintreeUIKit pod subspec somewhere, but it could very well be something else on my side that I missed. I did the usual cache clearing, derived data deleting, restarting, verifying linking flags, etc. to no avail...

**Comment by demerino** [comment] 2016-07-21 18:33
Actively looking into this now. The next release will make those headers public.

@darronschall If you have a moment, could you take a second to make a new project and try downloading just `pod 'Braintree/BraintreeUIKit', '4.4.0'` and using it in a similar way? Just to see if the issue is indeed related to the pod or something in the hybrid swift/objc project? If not - no worries.

I've made 2 vanilla projects (Objc and Swift) and haven't been able to reproduce this yet.

**Comment by darronschall** [comment] 2016-07-21 20:03
Thanks @demerino. I finally figured it out. It was the Derived Data... because of course it was. Nuked it to orbit for the third time and magically the linking issues went away. 

Once those new headers are in the new `BraintreeUIKit` pod, I think we're all set then. Sorry for the trouble.

**Comment by demerino** [comment] 2016-07-21 20:14
Great, closing this issue. Release `4.4.1` should be out tomorrow (or next week). Feel free to comment here if there are still issues after that. 

We appreciate the feedback and suggestions - great to have someone using the BTUIK classes 🎉 If you have suggestions, just open a PR or post another issue. We're looking to make BraintreeUIKit useful for a variety of integrations.

**Note** The release will change the module name to `UIKit` to match the docs. Thanks for pointing that out. You'll need to update your Podfile at that time.

**Closed by demerino** 2016-07-21 20:14 UTC
Labels: 4.x, backlog, UI

**Comment by civocr** [comment] 2016-11-16 05:00
Hey,

I figured I would bring this thread back to life for some context.

I'm upgrading my project to Braintree 4.x and I have a custom implementation to collect card details. My project needs access to BTUIKCVVFrontVectorArtView & BTUIKCVVBackVectorArtView

I have BraintreeDropIn in my pod, trying to make these 2 public using the manual process leaves me with the following error: duplicate interface definition for class 'BTUIKVectorArtView'
